### ISSUE TITLE
can‘t use the arrow key

### ISSUE THREAD

**Issue by Oosl** [YaSuenag/SimpleCom#1] opened 2019-08-29 03:03 UTC
First of all, thank you for your work so that I can connect to the serial port in the Windows terminal!
But when using the serial port, I often need to use  the arrow keys in vim or use it to find the first few commands, I hope you can fix this problem to make it better. thanks again.

**Comment by YaSuenag** [comment] 2019-08-29 11:57
Thank you for using SimpleCom!

In case of bash on Raspbian Jessie, arrow keys work fine.  
In case of vim-7.4.488-7+deb8u3, arrow keys work fine if you set terminal mode to ansi (`:set term=ansi`)

I use Windows 10 Pro (1903) with Japanese keyboard / Japanese locale. Serial device is Raspberry Pi 2 with Raspbian Jessie which is connected by TTL-232R-3V3.

I guess the problem which you saw is caused by language locale or keyboard layout. Can you share them?  
If key codes which are returned by [_getch()](https://docs.microsoft.com/cpp/c-runtime-library/reference/getch-getwch?view=vs-2019) are different from my laptop, I will try to add custom key mapper to SimpleCom.

**Comment by YaSuenag** [comment] 2019-08-29 11:59
Sorry, I closed this issue in mistake. Reopen.

I will close this issue when we find any solution for this.

**Comment by Oosl** [comment] 2019-09-03 01:37
I use Windows 10 Pro(1903) with Chinese keyboard / Chinese locale. Serial device is a router with OpenWrt by TTL-RS232. Do you need any other information?

**Comment by Oosl** [comment] 2019-09-04 08:28
I may have found the reason of this issue, and as you said, it is caused by keyboard layout.

In your code, you defined the keycode of arrow keys with 0x48(up) 0x4b(left) 0x4d(right) 0x50(down), and this is right in your Japanese keyboard. 

But in my chinese keyboard, the correct keycode is 0x26(up) 0x25(left) 0x27(right) 0x28(down) for arrow keys.

**Comment by YaSuenag** [comment] 2019-09-04 12:15
Thank you for the report!

I guess you saw [virtual key codes](https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes) (VK). SimpleCom uses [_getch()](https://docs.microsoft.com/cpp/c-runtime-library/reference/getch-getwch?view=vs-2019) to read keys. It would not return VKs.

However we might be able to use VKs to detect arrow keys. So I modified SimpleCom in https://github.com/YaSuenag/SimpleCom/commit/67f03e8f8bef322b2f2a54b9bc836a950198eb7e and I attached the binary on this comment. Can you try it?

[SimpleCom-issue1.zip](https://github.com/YaSuenag/SimpleCom/files/3574398/SimpleCom-issue1.zip)

In another point of view, we might pass raw keys instead of VT100 codes. Currently SimpleCom would pass VT100 escape sequences for arrow keys. If you use the terminal which did not support VT100, arrow keys would not work (the issue which you saw in vim).

Anyway, I hope that you try SimpleCom-issue1.zip . If it does not work well on your machines, I can provide raw keycode version to you.

**Comment by Oosl** [comment] 2019-09-05 02:11
I tried using SimpleCom-issue1.zip and it does not work well on my PC. Thanks for your reply!

**Comment by YaSuenag** [comment] 2019-09-05 05:25
Thanks for the evaluation! I will consider another solution.

**Comment by YaSuenag** [comment] 2019-09-05 05:52
Can you check `TERM` environment variable? It needs to be set to `vt100`. https://kb.iu.edu/d/acpy

**Comment by Oosl** [comment] 2019-09-05 06:49
I just tried to use it in cmd and found it to work fine. So it may be a problem with powershell, but I don't know how to set the environment variable TERM you mentioned above in powershell.

**Comment by YaSuenag** [comment] 2019-09-05 07:30
Thanks! I'm happy to hear that.  
Can you set environment variables on PowerShell as following? https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_environment_variables

BTW I think root cause of this issue is in ash profile. I guess you need to set `TERM` on your ash in OpenWrt like a `.bash_profile` in bash.  
If my guess is correct, I will update README.md and will close this issue.

**Comment by Oosl** [comment] 2019-09-06 03:08
Sorry for the problem with my previous description. 

Today I found that if I don't use it through the Windows Terminal, it works fine. I mentioned above that it works fine in cmd  is not because cmd, just because it didn't run in Windows Terminal.

On the other hand, I setted the TERM environment variable in PowerShell, and it's not work. Second, I don't think root cause of this issue is in ash profile. Because even for this reason, this can only fix my problem in OpenWrt, but can't fix the same problem in u-boot.

**Comment by YaSuenag** [comment] 2019-09-06 14:15
As I said SimpleCom would pass VT100 escape sequences for arrow keys, so it would not work well if the serial device did not support VT100 or its family. On that evidence serial console worked well when you set `TERM=vt100` to your OpenWrt.

I'm not familiar in U-Boot, but I guess it does not support VT100 by default. So if you can set `TERM` or equivalent configuration to its console, arrow keys might work fine.

Again, current SimpleCom needs VT100 compatible environment on serial device. It might work fine if we can replace equivalent sequences for arrow keys, but I have not found yet.

**Comment by Oosl** [comment] 2019-09-09 04:09
I set TERM=vt100 to OpenWrt, but It still doesn't work well.

**Comment by YaSuenag** [comment] 2019-09-09 07:07
Thank you for the report!

I'm wonder why it does not work even if you set `TERM` to on your OpenWrt terminal.  
But in case of OpenSSH on Windows sets [`TERM` to itself](https://github.com/PowerShell/openssh-portable/pull/185). So it might be correct as you confirmed.

I uploaded new SimpleCom prototype in this comment. It would set `TERM` before establishing serial connection https://github.com/YaSuenag/SimpleCom/commit/2252e92ca00c836d062864a7244a114ce057c965 . I hope it will work fine on your machine.

[SimpleCom-issue1-2.zip](https://github.com/YaSuenag/SimpleCom/files/3589058/SimpleCom-issue1-2.zip)

**Comment by Oosl** [comment] 2019-09-11 03:15
I'm sorry to reply now.
I have a bad news. [SimpleCom-issue1-2](https://github.com/YaSuenag/SimpleCom/files/3589058/SimpleCom-issue1-2.zip) is still the same as before and can't work properly. it work well in cmd or powershell terminal program which come with Windows10, but it still doesn't work well in Windows Terminal. All the same as before, no change.
So the problem maybe is not yours, it's Windows Terminal's.

**Comment by YaSuenag** [comment] 2019-09-11 13:27
Thank you for the report!

It is not a bug in SimpleCom as you said because https://github.com/YaSuenag/SimpleCom/commit/2252e92ca00c836d062864a7244a114ce057c965 would not work on Windows Terminal only. I will merge https://github.com/YaSuenag/SimpleCom/commit/2252e92ca00c836d062864a7244a114ce057c965 to master and update README.md to describe about VT100, then I will close this issue.

**Comment by YaSuenag** [comment] 2019-09-11 13:50
You can get fix version v0.1.2 from [release page](https://github.com/YaSuenag/SimpleCom/releases/tag/v0.1.2).

**Closed as completed by YaSuenag** 2019-09-11 13:50 UTC
Labels: documentation, enhancement

**Comment by Oosl** [comment] 2019-09-27 03:59
Hi YaSuenag, I found the reason of this really question today. because on my computer, the key value of function key obtained by `getch()` in Windows Terminal and in the cmd/powershell client come with Windows 10 are not same. The first key value is 0xe0 in cmd/powershell client, but that is 0x0 in Windows Terminal.

**Comment by Oosl** [comment] 2019-09-27 04:29
I modiffied SimpleCom.cpp like this [diff.txt](https://github.com/YaSuenag/SimpleCom/files/3660893/diff.txt) and It woks well now.

**Comment by YaSuenag** [comment] 2019-09-27 05:15
@Oosl thank you for the suggestion! But I wonder why this issue (includes return value of `_getch()`) is not appear on my laptop.

I checked your [diff.txt](https://github.com/YaSuenag/SimpleCom/files/3660893/diff.txt), but I cannot merge it yet.

According to [MSDN](https://docs.microsoft.com/cpp/c-runtime-library/reference/getch-getwch?view=vs-2019), we need to consider 0x00 and 0xE0 if we attempt to get arrow keys or function keys. In case of your patch, combination of 0xE0 and 0x3B would be treated as F1 key.

If you send PR about this, I will review and merge it. Can you work?

**Comment by Oosl** [comment] 2019-09-27 05:41
Like this [diff_fixed.txt](https://github.com/YaSuenag/SimpleCom/files/3661016/diff_fixed.txt)?

**Comment by YaSuenag** [comment] 2019-09-27 06:04
Yeah, it seems good.

I hope you to send PR to record your contribution!  
If you send PR, I will check further.
